/**
 * Rules settled in TypeScript, before any judge is called.
 *
 * Every rule answered here is a judge call not made and a verdict that cannot
 * drift between runs. The set is deliberately conservative: a rule belongs here
 * only when the page data decides it outright. Anything needing judgement —
 * "is this useful?", "does this read as made for search engines?" — is not a
 * candidate no matter how tempting the heuristic looks, because a wrong
 * deterministic answer is worse than an honest `unknown`.
 */
import type { RuleStatus } from "@/shared/guidelines/catalog";
import type { FetchedPage } from "./page-fetch";

export interface EvaluationContext {
  page: FetchedPage;
  /** Whether any internal link was seen pointing at this URL during the crawl. */
  hasInboundInternalLinks?: boolean;
  /** Site-level facts gathered once per audit. */
  site?: {
    hasAboutPage?: boolean;
    hasContactPage?: boolean;
  };
}

interface DeterministicResult {
  status: RuleStatus;
  evidence?: string;
  reason?: string;
}

type Evaluator = (ctx: EvaluationContext) => DeterministicResult;

/** `noindex` anywhere in the robots directives, meta or header. */
function isNoindexed(page: FetchedPage): boolean {
  return /\bnoindex\b/i.test(page.robotsMeta ?? "");
}

/** Narrows an unknown JSON node to a plain object. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Every `@type` in the page's JSON-LD, flattened across blocks and graphs. */
function schemaTypes(page: FetchedPage): string[] {
  const types: string[] = [];
  const walk = (node: unknown, depth: number): void => {
    if (depth > 6 || node === null || typeof node !== "object") return;
    if (Array.isArray(node)) {
      for (const item of node) walk(item, depth + 1);
      return;
    }
    if (!isRecord(node)) return;
    const record = node;
    const type = record["@type"];
    if (typeof type === "string") types.push(type);
    else if (Array.isArray(type)) {
      for (const t of type) if (typeof t === "string") types.push(t);
    }
    for (const value of Object.values(record)) walk(value, depth + 1);
  };
  for (const block of page.structuredData) walk(block, 0);
  return types;
}

/** First `author` name found anywhere in a JSON-LD tree. */
function authorFromSchema(node: unknown, depth: number): string | null {
  if (depth > 6 || node === null || typeof node !== "object") return null;
  if (Array.isArray(node)) {
    for (const item of node) {
      const found = authorFromSchema(item, depth + 1);
      if (found) return found;
    }
    return null;
  }
  if (!isRecord(node)) return null;
  const record = node;
  const author = record["author"];
  if (typeof author === "string" && author.trim()) return author.trim();
  if (isRecord(author)) {
    const name = author["name"];
    if (typeof name === "string" && name.trim()) return name.trim();
    const nested = authorFromSchema(author, depth + 1);
    if (nested) return nested;
  }
  for (const value of Object.values(record)) {
    const found = authorFromSchema(value, depth + 1);
    if (found) return found;
  }
  return null;
}

/**
 * Whether the page names a human author.
 *
 * Looks at JSON-LD first, because that is an explicit claim rather than a
 * guess, then falls back to a byline pattern in the visible text.
 */
function namedAuthor(page: FetchedPage): string | null {
  for (const block of page.structuredData) {
    const found = authorFromSchema(block, 0);
    if (found) return found;
  }
  // "By Jane Doe" / "Por Jane Doe", two or three capitalised words.
  const byline = page.bodyText
    .slice(0, 4000)
    .match(
      /\b(?:by|por|escrito por|written by)\s+([A-ZÁÉÍÓÚÑ][\p{L}.'-]+(?:\s+[A-ZÁÉÍÓÚÑ][\p{L}.'-]+){1,2})/u,
    );
  return byline?.[1] ?? null;
}

/** Author strings that name a machine rather than a person. */
const MACHINE_AUTHOR =
  /\b(ai|a\.i\.|artificial intelligence|chatgpt|gpt|claude|gemini|bot|robot|automated|generated by)\b/i;

/**
 * About/contact presence. The catalog asks this twice — once as a trust signal
 * (EAT-06) and once as a site-level requirement (SITE-02) — so the answer lives
 * in one function rather than being duplicated or aliased through the map.
 */
const evaluateAboutAndContact: Evaluator = (ctx) => {
  const site = ctx.site;
  if (
    !site ||
    (site.hasAboutPage === undefined && site.hasContactPage === undefined)
  ) {
    return { status: "unknown", reason: "Site pages were not inspected." };
  }
  return site.hasAboutPage || site.hasContactPage
    ? { status: "pass" }
    : {
        status: "fail",
        reason: "No about or contact page was found on the site.",
      };
};

const evaluators: Record<string, Evaluator> = {
  // Search technical requirements: the page must actually answer.
  "TECH-02": ({ page }) =>
    page.statusCode >= 200 && page.statusCode < 300
      ? { status: "pass" }
      : {
          status: "fail",
          evidence: `HTTP ${page.statusCode}`,
          reason: "The URL does not return a successful response.",
        },

  // Indexable content: text Googlebot can read without executing anything.
  "TECH-03": ({ page }) =>
    page.wordCount > 0
      ? { status: "pass" }
      : {
          status: "fail",
          reason:
            "No readable text in the served HTML; the content may be rendered client-side.",
        },

  "TECH-04": ({ page }) =>
    isNoindexed(page)
      ? {
          status: "fail",
          evidence: page.robotsMeta ?? "",
          reason: "The page asks search engines not to index it.",
        }
      : { status: "pass" },

  // Page experience starts at the transport.
  "PX-01": ({ page }) =>
    page.isHttps
      ? { status: "pass" }
      : {
          status: "fail",
          evidence: page.finalUrl,
          reason: "The page is served over plain HTTP.",
        },

  // Who: a named creator where a reader would ask for one.
  "WHO-01": (ctx) => {
    const author = namedAuthor(ctx.page);
    return author
      ? { status: "pass", evidence: author }
      : {
          status: "unknown",
          reason:
            "No author found in structured data or a byline; whether this page needs one is a judgement call.",
        };
  },

  // Naming a model as the author is called out explicitly by the guidance.
  "EAT-05": (ctx) => {
    const author = namedAuthor(ctx.page);
    if (!author) return { status: "unknown", reason: "No author to check." };
    return MACHINE_AUTHOR.test(author)
      ? {
          status: "fail",
          evidence: author,
          reason: "The byline credits an AI tool instead of a person.",
        }
      : { status: "pass", evidence: author };
  },

  // Trust signals a reader expects to be able to find.
  "EAT-06": evaluateAboutAndContact,

  // Same question, asked at site level by the catalog.
  "SITE-02": evaluateAboutAndContact,

  // Structured data must describe what the page actually shows.
  "SD-01": ({ page }) => {
    const types = schemaTypes(page);
    if (types.length === 0) return { status: "n/a" };
    return {
      status: "unknown",
      reason: "Whether the markup matches the visible content needs judgement.",
    };
  },

  // Review markup on a page carrying no reviews is the clearest schema abuse.
  "SD-02": ({ page }) => {
    const types = schemaTypes(page);
    const reviewTypes = types.filter((t) =>
      /review|rating|aggregaterating/i.test(t),
    );
    if (reviewTypes.length === 0) return { status: "n/a" };
    const mentionsReviews =
      /\b(review|reseñ|opinion|valoracion|rating|estrella|star)/i.test(
        page.bodyText,
      );
    return mentionsReviews
      ? { status: "pass", evidence: reviewTypes.join(", ") }
      : {
          status: "fail",
          evidence: reviewTypes.join(", "),
          reason:
            "The page carries review or rating markup but shows no reviews to a reader.",
        };
  },

  // Orphan pages, from the crawl's own link graph.
  "TECH-07": (ctx) => {
    if (ctx.hasInboundInternalLinks === undefined) {
      return { status: "unknown", reason: "The link graph was not available." };
    }
    return ctx.hasInboundInternalLinks
      ? { status: "pass" }
      : {
          status: "fail",
          reason: "No internal link points at this URL.",
        };
  },

  // On-page basics the crawl already measures.
  "ON-03": ({ page }) => {
    if (page.imagesTotal === 0) return { status: "n/a" };
    const missing = page.imagesMissingAlt;
    if (missing === 0) return { status: "pass" };
    return {
      status: missing === page.imagesTotal ? "fail" : "warn",
      evidence: `${missing} of ${page.imagesTotal} images have no alt text`,
      reason: "Content images should carry descriptive alt text.",
    };
  },
};

/**
 * Run the deterministic evaluator for a rule, if there is one.
 *
 * Returns null when the rule is not settled here, which routes it to a judge.
 * An evaluator that throws is treated as no answer rather than taking the whole
 * page evaluation down with it.
 */
export function evaluateDeterministic(
  ruleId: string,
  ctx: EvaluationContext,
): DeterministicResult | null {
  const evaluator = evaluators[ruleId];
  if (!evaluator) return null;
  try {
    return evaluator(ctx);
  } catch (error) {
    return {
      status: "unknown",
      reason: `Could not evaluate: ${error instanceof Error ? error.message : "unknown error"}`,
    };
  }
}
